# Pip Requirements: PyYAML
# Python version I used: 3.8.2
#
# Sooo, this is for a quite specific usecase, but, if you have Rancher
# installed, and you want to export all the containers' configs into a simple
# format, then all you have to do, is to go to the workloads view, select
# the containers of which the configs you want to export (or just click
# select all), and press "Donwload YAML". This will download a zip of all
# the configurations. Next, you want to create some folder in which you
# have this script, and a subdirectory called configs. Extract everything
# from the zip you've just downloaded into the configs subdirectory. Next,
# run this script, and voila, have your "simple.txt" to yourself.
#
#
#
# The directory structure:
#
#   mainDir
#   |
#   |__ configs
#   |  |
#   |  |__ all
#   |  |__ of
#   |  |__ your
#   |  |__ configs
#   |
#   |__ simple.txt (autogenerated by this script)
#   |__ simplify.py
#
#
#
# Here's the code:

from yaml import load
from yaml import CLoader as Loader
from os import listdir
from os import remove
from collections import namedtuple

Config = namedtuple("Config", "name image envs ports volumes")

files = listdir("configs")
configs = []
configInfos = []


for config in files:
	configTmp = open("configs/" + config, 'r')
	configs.append(load(configTmp, Loader=Loader))
	configTmp.close()

for config in configs:
	configTmp = config['spec']['template']['spec']['containers'][0]
	volumesTmp = config['spec']['template']['spec']['volumes'] if 'volumes' in config['spec']['template']['spec'] else ''
	ports = []
	volumeMounts = []
	volumeNames = []
	volumes = []
	envs = ''

	if 'ports' in configTmp:
		for port in configTmp['ports']:
			ports.append(port['name'])

	if 'volumeMounts' in configTmp:
		for volume in configTmp['volumeMounts']:
			volumeMounts.append(volume['mountPath'])

		for volume in volumesTmp:
			volumeNames.append(volume['hostPath']['path'])

		for i in range(volumeMounts.__len__()):
			volumes.append(volumeNames[i] + ':' + volumeMounts[i])

	if 'env' in configTmp:
		for env in configTmp['env']:
			envs += '\n                ' + env['name'] + ': ' + env['value']
	
	configInfos.append(Config(configTmp['name'], configTmp['image'], envs, ports, volumes))

if 'simple.txt' in listdir('.'):
	remove('simple.txt')

for config in configInfos:
	simple = open('simple.txt', 'a')
	
	simple.write(config.name + ':\n')
	simple.write('        Image: ' + str(config.image) + '\n')
	simple.write('        Envs: ' + str(config.envs) + '\n')
	simple.write('        Ports: ' + str(config.ports) + '\n')
	simple.write('        Volumes: ' + str(config.volumes) + '\n')
	simple.write('\n')
	simple.close()